places (
{
    "status": "Success",
    "list": [
        {
            "serial": "0000000006dd41f6",
            "address": "Munkkisaarenlaituri",
            "postalcode": "00150",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Hernesaari LHC",
            "latitude": 60.14951,
            "longitude": 24.92138,
            "group": "hernesaari",
            "alias": null
        },
        {
            "serial": "000000000f4919c9",
            "address": "Mannerheimintie 22-24",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Amos Rex",
            "latitude": 60.17065,
            "longitude": 24.93641,
            "group": "default",
            "alias": null
        },
        {
            "serial": "0000000019fb59c4",
            "address": "Tyynenmerenkatu 8",
            "postalcode": "00220",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Lansiterminaali 1",
            "latitude": 60.15432,
            "longitude": 24.9211,
            "group": "lansiterminaali",
            "alias": null
        },
        {
            "serial": "00000000342570c2",
            "address": "Sibeliuksen puisto",
            "postalcode": "00250",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Sibelius Monumentti",
            "latitude": 60.18203,
            "longitude": 24.91341,
            "group": "default",
            "alias": null
        },
        {
            "serial": "0000000038bf9618",
            "address": "Mattolaituri",
            "postalcode": "00140",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Kaivopuiston ranta",
            "latitude": 60.1538,
            "longitude": 24.95595,
            "group": "default",
            "alias": null
        },
        {
            "serial": "0000000038d83d41",
            "address": "Pakkahuoneenlaituri",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Pakkahuoneenlaituri",
            "latitude": 60.16544,
            "longitude": 24.95398,
            "group": "default",
            "alias": null
        },
        {
            "serial": "000000004ef3150d",
            "address": "Tyynenmerenkatu 14",
            "postalcode": "00180",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Lansiterminaali 2",
            "latitude": 60.14947,
            "longitude": 24.91438,
            "group": "lansiterminaali",
            "alias": null
        },
        {
            "serial": "0000000053c6c2be",
            "address": "Katajanokanlaituri, valopylvas",
            "postalcode": "00160",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Katajanokan laituri 2",
            "latitude": 60.16448,
            "longitude": 24.97323,
            "group": "katajanokka",
            "alias": null
        },
        {
            "serial": "00000000675d5200",
            "address": "paasisaankaynti",
            "postalcode": "00530",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Hakaniemen kauppahalli 1",
            "latitude": 60.17918,
            "longitude": 24.95141,
            "group": "default",
            "alias": null
        },
        {
            "serial": "000000006b087f40",
            "address": "Kaivokatu 2",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Ateneum",
            "latitude": 60.17002,
            "longitude": 24.94407,
            "group": "default",
            "alias": null
        },
        {
            "serial": "000000006b44cce7",
            "address": "Etelaranta",
            "postalcode": "00170",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Kauppatori",
            "latitude": 60.16762,
            "longitude": 24.95415,
            "group": "default",
            "alias": null
        },
        {
            "serial": "0000000074f765a7",
            "address": "Toolonlahdenranta 1",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Oodi",
            "latitude": 60.17368,
            "longitude": 24.9381,
            "group": "default",
            "alias": null
        },
        {
            "serial": "000000007b5207b6",
            "address": "Torikadun sisaankaynti",
            "postalcode": "00530",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Hakaniemen kauppahalli 2",
            "latitude": 60.17919,
            "longitude": 24.95181,
            "group": "default",
            "alias": null
        },
        {
            "serial": "0000000096918cfa",
            "address": "Lutherinkatu 3",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Temppeliaukion kirkko",
            "latitude": 60.173,
            "longitude": 24.92524,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000a53ed894",
            "address": "Hernesaarenlaituri",
            "postalcode": "00150",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Hernesaari LHD",
            "latitude": 60.14699,
            "longitude": 24.922,
            "group": "hernesaari",
            "alias": null
        },
        {
            "serial": "00000000aa852af1",
            "address": "Alexanterinkatu 24",
            "postalcode": "00170",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Senaatintori lantinen",
            "latitude": 60.16897,
            "longitude": 24.95222,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000afef4555",
            "address": "Pohjoisespa 41",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Stockmann",
            "latitude": 60.16829,
            "longitude": 24.94214,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000b33a8357",
            "address": "Narikkatorin sisaankaynti",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Kamppi",
            "latitude": 60.169,
            "longitude": 24.93288,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000cd16b8ef",
            "address": "Alexanterinkatu 20",
            "postalcode": "00170",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Senaatintori itainen",
            "latitude": 60.16899,
            "longitude": 24.95337,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000d747f075",
            "address": "Katajanokanlaituri 8",
            "postalcode": "00160",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Katajanokan terminaali",
            "latitude": 60.1638,
            "longitude": 24.96846,
            "group": "katajanokka",
            "alias": null
        },
        {
            "serial": "00000000e8a064a4",
            "address": "Munkkisaarenlaituri",
            "postalcode": "00150",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Hernesaari LHB",
            "latitude": 60.15133,
            "longitude": 24.92329,
            "group": "hernesaari",
            "alias": null
        },
        {
            "serial": "00000000f1124bca",
            "address": "Olympiaranta 1",
            "postalcode": "00100",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Olympiaterminaali",
            "latitude": 60.16075,
            "longitude": 24.95883,
            "group": "olympia",
            "alias": null
        },
        {
            "serial": "00000000fb7600be",
            "address": "Katajanokka",
            "postalcode": "00160",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Katajanokan laituri",
            "latitude": 60.16629,
            "longitude": 24.95957,
            "group": "katajanokka",
            "alias": null
        },
        {
            "serial": "00000000fdda10fe",
            "address": "Erottajankatu 11",
            "postalcode": "00130",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Dianapuisto",
            "latitude": 60.16531,
            "longitude": 24.9442,
            "group": "default",
            "alias": null
        },
        {
            "serial": "00000000fffb8cf0",
            "address": "Paalaituri",
            "postalcode": "00190",
            "city": "Helsinki",
            "country": "Finland",
            "description": "Suomenlinna",
            "latitude": 60.149,
            "longitude": 24.9843,
            "group": "default",
            "alias": null
        }
    ]
})