# Use postgres/example user/password credentials
#docker stop $(docker ps -a -q)
#docker rm $(docker ps -a -q)
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432